services:
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            interval: 1s
            timeout: 3s
            retries: 5
    backend:
        stdin_open: true
        tty: true
        depends_on:
            redis:
                condition: service_healthy
        build:
            dockerfile: ./.docker/Dockerfile.backend
            context: .
            target: install
        volumes:
            - ./backend/src:/app/backend/src:cached
            - ./prisma:/app/prisma:cached
        environment:
            SERVER_PORT: 8000
            DATABASE_URL: "postgresql://postgres:Hidemeplease!!1@hmp2024.cakclrq2opqj.ap-northeast-2.rds.amazonaws.com:5432/hidemeplease"
            NODE_ENV: development
        env_file:
            - .env
        ports:
            - '8000:8000'
        command: ['pnpm', 'run', 'dev']
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 2G
