export enum ErrorCodes {
	COULD_NOT_VERIFY = 'COULD_NOT_VERIFY',
	JWT_INVALID_OR_EXPIRED = 'JWT_INVALID_OR_EXPIRED',
	USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
	WALLET_DOES_NOT_EXIST = 'WALLET_DOES_NOT_EXIST',
}
