export enum PointTransactionType {
  EARNED = 'EARNED',
  SPENT = 'SPENT',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED'
}

export enum PointSource {
  CHECK_IN = 'CHECK_IN',
  GROUP_BONUS = 'GROUP_BONUS',
  PURCHASE = 'PURCHASE',
  REWARD = 'REWARD',
  REFERRAL = 'REFERRAL',
  EVENT = 'EVENT',
  ADMIN_GRANT = 'ADMIN_GRANT',
  ADMIN_DEDUCT = 'ADMIN_DEDUCT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  REFUND = 'REFUND',
  SIREN_POST = 'SIREN_POST',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPT = 'FRIEND_ACCEPT',
  OTHER = 'OTHER'
}